# Generated by Django 5.2.5 on 2025-08-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
